name: TeamFlow CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd catalyst/functions/fetchTeamData && npm install
        cd ../calculateCapacity && npm install
        cd ../aggregatePriorities && npm install
        cd ../smartAssign && npm install
        cd ../detectOverload && npm install
        cd ../sendNotification && npm install
        
    - name: Run Unit Tests
      run: |
        cd catalyst/functions/fetchTeamData && npm test
        cd ../calculateCapacity && npm test
        cd ../aggregatePriorities && npm test
        cd ../smartAssign && npm test
        cd ../detectOverload && npm test
        cd ../sendNotification && npm test

  integration-test:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Start Mock Server
      run: |
        cd samples/mock_zoho_api_server
        npm install
        npm start &
        sleep 5 # Wait for server to start
        
    - name: Run Integration Tests
      run: |
        # Assuming integration tests are in catalyst/tests/integration
        # and they are configured to hit localhost:3000
        # cd catalyst/tests/integration && npm install && npm test
        echo "Running integration tests..."
        # Placeholder for actual integration test command

  deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Catalyst CLI
      run: npm install -g zcatalyst-cli
      
    - name: Deploy to Catalyst
      env:
        ZOHO_CATALYST_TOKEN: ${{ secrets.ZOHO_CATALYST_TOKEN }}
      run: |
        # catalyst deploy --project teamflow-command-center
        echo "Deploying to Catalyst..."

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3
    
    - name: Package Extension
      run: |
        zip -r teamflow-extension.zip teamflow-command-center -x "catalyst/*" "infra/*" "samples/*"
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./teamflow-extension.zip
        asset_name: teamflow-extension.zip
        asset_content_type: application/zip
